### ISSUE TITLE
Let's go Awesome-crystal!

### ISSUE THREAD

**Issue by rwnx** [wontruefree/prime#1]
Hi! 

I saw your repo on the awesome-crystal PRs - and you gave me the kick up the ass to get mine up there. The project's already over 30d, so it's just the regular builds to satisfy: 

Do you have a preference for travis? I recently wrote a github actions workflow to do this:

```
name: Crystal CI

on:
  push:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
    - name: Run Lint
      run: crystal tool format --check
```

Let me know what you think and I'd be happy to put together a PR. 
🤟
